### ISSUE TITLE
"Pure Digital" heart rate update problem

### ISSUE THREAD

**Issue by mspinning** [fagalto/ConnectIQ#1]
Hi,

1: I really like you your watch face. And thanks for open sourcing it :)
2: My problem is, that the heart rate only updates when the minutes are updated. Is this a bug or did i miss some configuration.

I use a forrunner 745

Thank for you help

**Comment by fagalto** [comment]
hr, and all data are refreshed once per minute. Only seconds are redrawn in
1second  interval.

wt., 9 mar 2021, 15:04 użytkownik Marco <notifications@github.com> napisał:

**Comment by mspinning** [comment]
OK. thanks for you help, I will have a look if i can change it for me :)
